INSERT INTO Questions (Question_Type, question, Choice_1, Choice_2, Choice_3, Choice_4, correct_Choice, Crs_ID) VALUES
('MCQ', 'Which framework is designed for real-time data processing?', 'Apache Hadoop', 'Apache Spark', 'Apache Storm', 'Apache Kafka', 'Apache Storm',21),
('MCQ', 'What is HDFS an acronym for?', 'Hadoop Data File System', 'High-Definition File System', 'Hadoop Distributed File System', 'Highly Distributed File System', 'Hadoop Distributed File System',21),
('MCQ', 'Which of the following is not a NoSQL database type?', 'Document', 'Graph', 'Key-Value', 'Table-Structured', 'Table-Structured',21),
('MCQ', 'What does the term "Big Data" primarily refer to?', 'Large datasets that cannot be processed by traditional databases', 'Any kind of data, regardless of its size', 'Data from social media', 'Only structured data', 'Large datasets that cannot be processed by traditional databases',21),
('MCQ', 'Which technology is used for batch processing of Big Data?', 'Apache Cassandra', 'Apache HBase', 'Apache Hadoop', 'Apache Spark', 'Apache Hadoop',21),
('MCQ', 'What role does Zookeeper play in a Hadoop Cluster?', 'Data Storage', 'Resource Management', 'Cluster Coordination', 'Data Processing', 'Cluster Coordination',21),
('MCQ', 'Which of the following is a characteristic feature of Big Data?', 'Veracity', 'Velocity', 'Volume', 'All of the above', 'All of the above',21),
('MCQ', 'What is Apache Pig used for?', 'Data Analysis', 'Machine Learning', 'Real-time Streaming', 'Graph Processing', 'Data Analysis',21),
('MCQ', 'Which of the following best describes Data Lakes?', 'Stores raw data in its native format', 'Used for generating reports', 'Optimized for data warehousing', 'None of the above', 'Stores raw data in its native format',21),
('MCQ', 'MapReduce is associated with which of the following?', 'Data Visualization', 'Machine Learning Algorithms', 'Processing of Big Data', 'Real-time Data Analysis', 'Processing of Big Data',21),
('True/False','Big Data solutions can only run on cloud platforms.', 'True', 'False', Null, Null, 'False',21),
('True/False','Apache Kafka is a distributed streaming platform.', 'True', 'False', Null, Null, 'True',21),
('True/False','Hadoop MapReduce jobs can be written in Python.', 'True', 'False', Null, Null, 'True',21),
('True/False','NoSQL databases do not require fixed table schemas.', 'True', 'False', Null, Null, 'True',21),
('True/False','Big Data technologies are exclusively for IT professionals.', 'True', 'False', Null, Null, 'False',21),
('True/False','Data Scientists primarily deal with structured data.', 'True', 'False', Null, Null, 'False',21),
('True/False','Machine Learning cannot be applied to Big Data analytics.', 'True', 'False', Null, Null, 'False',21),
('True/False','The velocity in Big Data refers to the speed of data in and out.', 'True', Null, Null, 'False', 'True',21),
('True/False','Big Data analytics can predict future trends from past data.', 'True', Null, Null, 'False', 'True',21),
('True/False','SQL cannot be used to query Big Data.', 'True', 'False', Null, Null, 'False',21);