insert into Courses (Cr_Name, Hours, Topic_ID) values ('Introduction to Programming', 22, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Web Development', 98, 7);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Data Science', 96, 3);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Machine Learning', 70, 1);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Cyber Security', 132, 2);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Mobile App Development', 131, 11);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Data base fundamental', 28, 8);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Data base advance', 136, 8);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Python', 105, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Operation system', 92, 10);
insert into Courses (cr_Name, Hours, Topic_ID) values ('XML', 129, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('SQL BI', 143, 12);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Excel', 131, 12);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Data Warehouse', 33, 8);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Statistics and probability', 76, 3);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Presentations skills', 126, 13);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Tableau', 24, 12);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Cloud', 60, 14);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Freelance', 130, 15);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Power BI', 13, 12);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Big Data', 128, 8);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Color theory', 126,16);
insert into Courses (cr_Name, Hours, Topic_ID) values ('CV and interviewing Skills', 143, 13);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Communications skills', 20, 13);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Network', 111, 5);
insert into Courses (cr_Name, Hours, Topic_ID) values ('C++', 41, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('AI', 121, 1);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Laravel', 99, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('PHP', 48, 6);
insert into Courses (cr_Name, Hours, Topic_ID) values ('Pattern design', 105, 6);
