-- Insert MCQ Questions
INSERT INTO Questions (QUESTION_TYPE, QUESTION, choice_1, choice_2, choice_3, choice_4, correct_choice,Crs_ID)
VALUES 
('MCQ', 'What does the term "phishing" refer to in cybersecurity?', 'A technique used to gain unauthorized access to a system by exploiting vulnerabilities', 'A type of malware that spreads through email attachments', 'A social engineering attack that involves tricking individuals into revealing sensitive information', 'A cryptographic technique used to protect data during transmission', 'A social engineering attack that involves tricking individuals into revealing sensitive information',5),
('MCQ', 'What is the primary purpose of a firewall in cybersecurity?', 'To encrypt data transmissions', 'To detect and remove malware from a system', 'To prevent unauthorized access to a network', 'To recover lost data in the event of a cyberattack', 'To prevent unauthorized access to a network',5),
('MCQ', 'Which of the following is an example of a "zero-day exploit"?', 'A software vulnerability that has been publicly disclosed but for which no patch is available', 'A cyberattack that targets a specific individual or organization', 'A type of malware that spreads rapidly across multiple systems', 'A security flaw that is exploited before the software vendor is aware of it', 'A security flaw that is exploited before the software vendor is aware of it',5),
('MCQ', 'What is the purpose of a Virtual Private Network (VPN) in cybersecurity?', 'To encrypt data transmissions between two endpoints', 'To scan for and remove viruses from a computer system', 'To monitor network traffic for suspicious activity', 'To provide physical security for servers and data centers', 'To encrypt data transmissions between two endpoints',5),
('MCQ', 'Which of the following is a common method used to authenticate users in cybersecurity?', 'Biometric authentication', 'Social engineering', 'Firewall configuration', 'Network intrusion detection', 'Biometric authentication',5),
('MCQ', 'What does the term "ransomware" refer to in cybersecurity?', 'A type of malware that steals sensitive information from a system', 'A security protocol used to protect data during transmission', 'A cyberattack that targets specific individuals or organizations', 'A type of malware that encrypts files and demands payment for their release', 'A type of malware that encrypts files and demands payment for their release',5),
('MCQ', 'What is the purpose of penetration testing in cybersecurity?', 'To detect and remove malware from a system', 'To evaluate the security of a system by simulating cyberattacks', 'To monitor network traffic for signs of intrusion', 'To recover data lost due to a cyberattack', 'To evaluate the security of a system by simulating cyberattacks',5),
('MCQ', 'Which of the following is an example of a "denial-of-service (DoS)" attack?', 'A hacker gains unauthorized access to a system by exploiting a vulnerability', 'A malware infection spreads rapidly across multiple systems', 'A cybercriminal floods a website with traffic to make it unavailable to legitimate users', 'A phishing email tricks individuals into revealing their login credentials', 'A cybercriminal floods a website with traffic to make it unavailable to legitimate users',5),
('MCQ', 'What is the purpose of encryption in cybersecurity?', 'To prevent unauthorized access to sensitive information', 'To detect and remove malware from a system', 'To monitor network traffic for suspicious activity', 'To recover lost data in the event of a cyberattack', 'To prevent unauthorized access to sensitive information',5),
('MCQ', 'What does the term "two-factor authentication" refer to in cybersecurity?', 'A security measure that requires users to authenticate using two different methods', 'A type of malware that spreads through email attachments', 'A cryptographic technique used to protect data during transmission', 'A social engineering attack that involves tricking individuals into revealing sensitive information', 'A security measure that requires users to authenticate using two different methods',5);

-- Insert True/False Questions
INSERT INTO Questions (QUESTION_TYPE, QUESTION, choice_1, choice_2, choice_3, choice_4, correct_choice,Crs_ID)
VALUES 
('TrueFalse', 'A brute-force attack is a type of cyberattack that attempts to guess passwords or encryption keys.','True','False',Null,Null, 'True',5),
('TrueFalse', 'A distributed denial-of-service (DDoS) attack involves flooding a network or server with traffic from multiple sources to disrupt its normal operation.','True','False',Null,Null, 'True',5),
('TrueFalse', 'Cybersecurity incidents can have financial, reputational, and legal consequences for organizations.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'Social engineering attacks rely on exploiting vulnerabilities in software systems to gain unauthorized access to a network.', 'True','False',Null,Null,'False',5),
('TrueFalse', 'Patch management is the process of applying updates and fixes to software systems to address security vulnerabilities.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'An intrusion detection system (IDS) monitors network traffic for suspicious activity and issues alerts when potential threats are detected.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'Encryption keys are used to decrypt encrypted data and reveal its original content.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'A data breach occurs when sensitive information is accessed, disclosed, or stolen without authorization.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'A firewall is a hardware or software-based security system that controls incoming and outgoing network traffic based on predetermined security rules.', 'True','False',Null,Null,'True',5),
('TrueFalse', 'Cybersecurity awareness training for employees is an important measure to mitigate the risk of insider threats.', 'True','False',Null,Null,'True',5);
