
INSERT INTO QUESTIONS (QUESTION_TYPE, QUESTION, choice_1, choice_2, choice_3, choice_4, correct_choice, crs_ID)
VALUES 
('MCQ', 'What is Laravel?', 'A PHP framework', 'A JavaScript library', 'A database management system', 'An operating system', 'A PHP framework', 28),
('True/False', 'Laravel follows the MVC architectural pattern.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'Which of the following databases is commonly used with Laravel?', 'MySQL', 'MongoDB', 'SQLite', 'Oracle', 'MySQL', 28),
('MCQ', 'What is the purpose of Composer in Laravel?', 'Dependency management', 'Authentication', 'Routing', 'Template rendering', 'Dependency management', 28),
('True/False', 'Blade is the default templating engine used in Laravel.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is Eloquent in Laravel?', 'An ORM (Object-Relational Mapping) included with Laravel', 'A JavaScript framework', 'A server-side rendering engine', 'A database management tool', 'An ORM (Object-Relational Mapping) included with Laravel', 28),
('MCQ', 'What is the purpose of Laravel Artisan?', 'Command-line interface for Laravel', 'A JavaScript framework', 'A database management tool', 'A PHP debugger', 'Command-line interface for Laravel', 28),
('True/False', 'Laravel provides built-in support for user authentication.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is the role of Middleware in Laravel?', 'Handle HTTP requests before they reach the application', 'Render HTML templates', 'Handle database queries', 'Manage session data', 'Handle HTTP requests before they reach the application', 28),
('MCQ', 'Which directory contains the configuration files in a Laravel application?', 'config', 'public', 'resources', 'storage', 'config', 28),
('True/False', 'Laravel supports method injection in its controllers.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What does MVC stand for?', 'Model-View-Controller', 'Model-View-Command', 'Model-View-Component', 'Model-View-Configuration', 'Model-View-Controller', 28),
('MCQ', 'Which command is used to create a new Laravel project?', 'laravel new', 'create-laravel', 'make-laravel', 'generate-laravel', 'laravel new', 28),
('True/False', 'Laravel provides built-in support for caching.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is the purpose of the .env file in Laravel?', 'To store environment-specific configuration', 'To define routes', 'To store database schema', 'To define middleware', 'To store environment-specific configuration', 28),
('MCQ', 'Which of the following is NOT a feature of Laravel?', 'Built-in testing support', 'Migrations', 'RESTful routing', 'Built-in support for NoSQL databases', 'Built-in support for NoSQL databases', 28),
('True/False', 'Laravel has a built-in task scheduler.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is Laravel Valet?', 'A development environment for macOS', 'A templating engine', 'A JavaScript library', 'A database management tool', 'A development environment for macOS', 28),
('MCQ', 'What does the Laravel routing system allow you to do?', 'Map HTTP requests to controller actions', 'Handle database operations', 'Render HTML templates', 'Create database migrations', 'Map HTTP requests to controller actions', 28),
('True/False', 'Laravel provides built-in support for sending emails.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'Which of the following is NOT a Laravel relationship type?', 'BelongsToMany', 'BelongsTo', 'HasMany', 'HasOne', 'BelongsToMany', 28),
('MCQ', 'What is Laravel Mix?', 'A Webpack wrapper', 'A PHP framework', 'A database management tool', 'A testing suite', 'A Webpack wrapper', 28),
('True/False', 'Laravel uses PSR-4 autoloading standards.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is the purpose of Laravel Blade templating engine?', 'To simplify the process of creating views', 'To handle database migrations', 'To manage environment variables', 'To define routes', 'To simplify the process of creating views', 28),
('MCQ', 'Which of the following commands is used to run database migrations in Laravel?', 'php artisan migrate', 'php artisan migrate:rollback', 'php artisan migrate:refresh', 'php artisan migrate:reset', 'php artisan migrate', 28),
('True/False', 'Laravel applications can be easily deployed to Heroku.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is the purpose of Laravels database migrations?', 'To manage database schema changes', 'To render HTML templates', 'To handle HTTP requests', 'To manage environment variables', 'To manage database schema changes', 28),
('MCQ', 'Which directory contains the views in a Laravel application?', 'resources/views', 'app/views', 'public/views', 'storage/views', 'resources/views', 28),
('True/False', 'Laravel applications can be developed using test-driven development (TDD) principles.', 'True', 'False', NULL, NULL, 'True', 28),
('MCQ', 'What is the purpose of Laravels Eloquent ORM?', 'To interact with the database', 'To handle HTTP requests', 'To render HTML templates', 'To manage environment variables', 'To interact with the database', 28);