
-- Insert questions for the Pattern Design course into QUESTIONS table
INSERT INTO QUESTIONS (QUESTION_TYPE, QUESTION, choice_1, choice_2, choice_3, choice_4, correct_choice, crs_ID)
VALUES 
('MCQ', 'What is a design pattern in software engineering?', 'A general, reusable solution to a commonly occurring problem within a given context', 'The appearance of a graphical user interface', 'A tool for creating artistic patterns', 'A specific solution to a single problem', 'A general, reusable solution to a commonly occurring problem within a given context', 30),
('True/False', 'Design patterns can only be applied to object-oriented programming languages.', 'False', 'True', NULL, NULL, 'False', 30),
('MCQ', 'Which of the following is NOT a category of design patterns according to the Gang of Four?', 'Behavioral patterns', 'Structural patterns', 'Creational patterns', 'Logical patterns', 'Logical patterns', 30),
('MCQ', 'What is the purpose of the Singleton design pattern?', 'To ensure a class has only one instance and provide a global point of access to it', 'To create objects without specifying the class of object to be created', 'To define an interface for creating an object, but let subclasses alter the type of objects that will be created', 'To represent how objects interact in a network', 'To ensure a class has only one instance and provide a global point of access to it', 30),
('True/False', 'Design patterns can improve the maintainability and scalability of software systems.', 'True', 'False', NULL, NULL, 'True', 30),
('MCQ', 'Which design pattern is used to separate abstraction from implementation?', 'Bridge Pattern', 'Factory Method Pattern', 'Singleton Pattern', 'Decorator Pattern', 'Bridge Pattern', 30),
('MCQ', 'What is the Observer design pattern used for?', 'To define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically', 'To create objects without specifying the class of object to be created', 'To ensure a class has only one instance and provide a global point of access to it', 'To define an interface for creating an object, but let subclasses alter the type of objects that will be created', 'To define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically', 30),
('True/False', 'The Adapter pattern allows incompatible interfaces to work together.', 'True', 'False', NULL, NULL, 'True', 30),
('MCQ', 'Which design pattern is used to provide a way to access elements of an aggregate object sequentially without exposing its underlying representation?', 'Iterator Pattern', 'Facade Pattern', 'Proxy Pattern', 'Chain of Responsibility Pattern', 'Iterator Pattern', 30),
('MCQ', 'In the Strategy pattern, what does the context class do?', 'It maintains a reference to the current strategy object', 'It defines the interface for the algorithm', 'It encapsulates the algorithm', 'It delegates the responsibility of defining the algorithm to subclasses', 'It maintains a reference to the current strategy object', 30),
('True/False', 'The Command pattern encapsulates a request as an object, thereby allowing for parameterization of clients with queues, requests, and operations.', 'True', 'False', NULL, NULL, 'True', 30),
('MCQ', 'What is the intent of the Abstract Factory pattern?', 'To provide an interface for creating families of related or dependent objects without specifying their concrete classes', 'To ensure a class has only one instance and provide a global point of access to it', 'To define an interface for creating an object, but let subclasses alter the type of objects that will be created', 'To represent how objects interact in a network', 'To provide an interface for creating families of related or dependent objects without specifying their concrete classes', 30),
('MCQ', 'Which design pattern is used to define an interface for creating an object, but let subclasses alter the type of objects that will be created?', 'Factory Method Pattern', 'Abstract Factory Pattern', 'Singleton Pattern', 'Prototype Pattern', 'Factory Method Pattern', 30),
('True/False', 'In the State pattern, an object appears to change its class when the class it passes calls through to switches its internal state.', 'True', 'False', NULL, NULL, 'True', 30),
('MCQ', 'What problem does the Decorator pattern solve?', 'It attaches additional responsibilities to an object dynamically', 'It ensures a class has only one instance and provides a global point of access to it', 'It encapsulates the algorithm', 'It represents how objects interact in a network', 'It attaches additional responsibilities to an object dynamically', 30),
('MCQ', 'Which design pattern is used to provide a surrogate or placeholder for another object to control access to it?', 'Proxy Pattern', 'Composite Pattern', 'Bridge Pattern', 'Adapter Pattern', 'Proxy Pattern', 30),
('True/False', 'The Visitor pattern represents a snapshot of an object’s state.', 'True', 'False', NULL, NULL, 'False', 30),
('MCQ', 'What is the intent of the Prototype pattern?', 'To specify the kinds of objects to create using a prototypical instance', 'To ensure a class has only one instance and provide a global point of access to it', 'To encapsulate the algorithm', 'To represent how objects interact in a network', 'To specify the kinds of objects to create using a prototypical instance', 30),
('MCQ', 'Which design pattern is used to handle communication between objects in a chain-like structure?', 'Chain of Responsibility Pattern', 'Proxy Pattern', 'Flyweight Pattern', 'Mediator Pattern', 'Chain of Responsibility Pattern', 30),
('True/False', 'The Flyweight pattern is used to minimize memory usage by sharing as much as possible with similar objects.', 'True', 'False', NULL, NULL, 'True', 30),
('MCQ', 'What problem does the Command pattern solve?', 'It encapsulates a request as an object, thereby allowing for parameterization of clients with queues, requests, and operations', 'It provides an interface for creating families of related or dependent objects without specifying their concrete classes', 'It ensures a class has only one instance and provides a global point of access to it', 'It defines an interface for creating an object, but lets subclasses alter the type of objects that will be created', 'It encapsulates a request as an object, thereby allowing for parameterization of clients with queues, requests, and operations', 30),
('MCQ', 'Which design pattern is used to encapsulate a request as an object, thereby allowing for parameterization of clients with queues, requests, and operations?', 'Command Pattern', 'Interpreter Pattern', 'Memento Pattern', 'Observer Pattern', 'Command Pattern', 30),
('True/False', 'The Memento pattern captures and externalizes an objects internal state so that it can be restored later, all without violating encapsulation.', 'True', 'False', NULL, NULL, 'True', 30);
