
INSERT INTO QUESTIONS (QUESTION_TYPE, QUESTION, choice_1, choice_2, choice_3, choice_4, correct_choice, crs_ID)
VALUES 
('MCQ', 'What does PHP stand for?', 'Personal Hypertext Processor', 'PHP: Hypertext Preprocessor', 'Public Hypertext Processor', 'Personal Home Page', 'PHP: Hypertext Preprocessor', 29),
('True/False', 'PHP is a server-side scripting language.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'Which of the following is NOT a data type in PHP?', 'Integer', 'Float', 'Boolean', 'Double', 'Double', 29),
('MCQ', 'What function in PHP is used to redirect the user to another web page?', 'header()', 'redirect()', 'location()', 'forward()', 'header()', 29),
('True/False', 'PHP code is executed on the server.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'Which of the following is used to denote comments in PHP?', '//', '#', '/* */', '--', '//', 29),
('MCQ', 'Which PHP function is used to read a file?', 'fopen()', 'file_get_contents()', 'readfile()', 'fread()', 'file_get_contents()', 29),
('True/False', 'In PHP, "===" checks both value and type equality.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'What is the purpose of the implode() function in PHP?', 'To split a string into an array', 'To convert an array into a string', 'To reverse a string', 'To search for a substring within a string', 'To convert an array into a string', 29),
('MCQ', 'Which of the following is used to declare a constant in PHP?', 'define()', 'constant()', 'const()', 'var()', 'define()', 29),
('True/False', 'PHP stands for "Hypertext Markup Language".', 'False', 'True', NULL, NULL, 'False', 29),
('MCQ', 'What is the correct way to start a session in PHP?', 'session_start()', 'start_session()', 'init_session()', 'begin_session()', 'session_start()', 29),
('MCQ', 'In PHP, how would you output "Hello, World!"?', 'echo "Hello, World!";', 'print("Hello, World!");', 'document.write("Hello, World!");', 'printf("Hello, World!");', 'echo "Hello, World!";', 29),
('True/False', 'PHP is a case-sensitive language.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'Which of the following is used to concatenate strings in PHP?', '.', '+', '-', ',', '.', 29),
('MCQ', 'Which of the following is used to check if a file exists in PHP?', 'file_exists()', 'file_open()', 'file_check()', 'file_create()', 'file_exists()', 29),
('True/False', 'PHP can only be embedded into HTML files.', 'False', 'True', NULL, NULL, 'False', 29),
('MCQ', 'What is the correct way to end a PHP statement?', ';', '.', ':', ',', ';', 29),
('MCQ', 'Which of the following is NOT a superglobal in PHP?', '$_SESSION', '$_GET', '$_POST', '$_REQUEST', '$_REQUEST', 29),
('True/False', 'PHP supports multiple inheritance.', 'False', 'True', NULL, NULL, 'False', 29),
('MCQ', 'What function in PHP is used to return the length of a string?', 'strlen()', 'strlength()', 'length()', 'stringlength()', 'strlen()', 29),
('MCQ', 'Which PHP function is used to open a file?', 'fopen()', 'file_open()', 'open_file()', 'readfile()', 'fopen()', 29),
('True/False', 'PHP is a compiled language.', 'False', 'True', NULL, NULL, 'False', 29),
('MCQ', 'Which of the following is used to execute a block of code repeatedly in PHP?', 'while loop', 'for loop', 'do-while loop', 'foreach loop', 'while loop', 29),
('MCQ', 'What is the correct way to declare an array in PHP?', '$arr = array();', '@arr = [];', 'array $arr;', '$arr = ();', '$arr = array();', 29),
('True/False', 'PHP is mainly used for client-side scripting.', 'False', 'True', NULL, NULL, 'False', 29),
('MCQ', 'Which PHP function is used to delete a file?', 'unlink()', 'delete_file()', 'remove()', 'file_delete()', 'unlink()', 29),
('MCQ', 'What is the correct way to declare a variable in PHP?', '$var = value;', '@var = value;', 'variable var = value;', 'var = value;', '$var = value;', 29),
('True/False', 'PHP code must be enclosed within <?php ?> tags.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'In PHP, what is the correct way to declare a class property as static?', 'public static $variable;', 'static $variable;', '$variable = static;', 'static public $variable;', 'public static $variable;', 29),
('MCQ', 'Which of the following is NOT a control structure in PHP?', 'if-else', 'for loop', 'repeat-until', 'when-then', 'when-then', 29),
('True/False', 'PHP supports automatic type conversion.', 'True', 'False', NULL, NULL, 'True', 29),
('MCQ', 'What PHP function is used to get the current date and time?', 'date()', 'time()', 'now()', 'datetime()', 'date()', 29);