insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('3D Art', 7, 39, 29, 7);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Game Programming', 5, 24, 13, 7);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Game Art', 5, 18, 29, 7);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('VFX Compositing', 1, 23, 12, 7);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('2D ANIMATION AND MOTION GRAPHICS', 8, 34, 15, 7);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Systems Administration', 2, 29, 23, 8);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Cyber Security', 3, 29, 13, 8);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Telecom Applications Development', 9, 24, 22, 8);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Cloud Architecture', 8, 25, 14, 8);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Wireless Communications', 1, 23, 28, 8);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Geographic information Systems', 7, 30, 23, 9);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Enterprise Resource Planning', 7, 35, 17, 9);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Architecture Engineering and Construction Informatics', 2, 23, 25, 9);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Data Management', 9, 32, 25, 9);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Data Science', 1, 48, 23, 9);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Geographic information Systems', 3, 45, 12, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Computer Aided Design', 9, 46, 12, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Systems Administration', 6, 22, 14, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Systems Development (PD,SWA)', 7, 42, 16, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Open Source Applications Development', 2, 43, 20, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Enterprise & Web Apps Development - Java', 7, 50, 19, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Native Mobile Applications Development', 5, 40, 26, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Professional Web Development & BI', 1, 34, 25, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Web & User Interface Development', 9, 49, 14, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Telecom Applications Development', 5, 28, 22, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Architecture Engineering and Construction Informatics', 6, 36, 19, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Internet of Things Applications Development', 1, 45, 26, 10);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('AI and Machine Learning Engineer', 5, 43, 26, 12);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Software Testing & Quality Assurance', 8, 23, 24, 13);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Embeded System Design', 8, 33, 15, 6);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Digital IC Design', 9, 44, 12, 6);
insert into Track (T_Name, Duration, Capacity, No_Courses, Dept_ID) values ('Wireless Communication', 6, 22, 14, 6);
